#!/usr/bin/env node
// The Codex skill package (.codex-plugin/skills/) is generated by
// scripts/build-codex-skills.js. These tests fail when the committed tree is
// stale, contains extra files, or lets Codex invoke the mode controller
// implicitly.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const {
  CONTROLLER,
  NAMES,
  ONE_SHOT_NAMES,
  ONE_SHOT_OPENAI_CONFIG,
  OPENAI_CONFIG,
  OUTPUT_ROOT,
  PORTABLE_OPENAI_CONFIG,
  canonicalPath,
  generatedFiles,
  outPath,
  portableConfigPath,
} = require('../scripts/build-codex-skills');

const ROOT = path.join(__dirname, '..');

function filesUnder(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const file = path.join(dir, entry.name);
    return entry.isDirectory() ? filesUnder(file) : [file];
  });
}

test('Codex manifest points at the generated skill root', () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, '.codex-plugin', 'plugin.json'), 'utf8'));
  assert.equal(manifest.skills, './.codex-plugin/skills/');
});

test('committed Codex skill tree contains exactly the generated files', () => {
  const relative = file => path.relative(OUTPUT_ROOT, file).replace(/\\/g, '/');
  const actual = filesUnder(OUTPUT_ROOT).map(relative).sort();
  const expected = [...generatedFiles().keys()].map(relative).sort();
  assert.deepEqual(actual, expected, 'stale files found — run: node scripts/build-codex-skills.js');
  assert.equal(NAMES.length, 6);
});

test('Codex controller matches the generator and contains no canonical rules body', () => {
  const onDisk = fs.readFileSync(outPath('ponytail'), 'utf8');
  assert.equal(onDisk, CONTROLLER, 'stale — run: node scripts/build-codex-skills.js');

  const canonical = fs.readFileSync(canonicalPath('ponytail'), 'utf8');
  assert.notEqual(onDisk, canonical);
  for (const marker of ['## The ladder', '## Rules', '## Intensity', '## When NOT to be lazy']) {
    assert.equal(onDisk.includes(marker), false, `controller copied canonical section: ${marker}`);
  }
});

test('only the Codex controller disables implicit invocation', () => {
  const configPath = path.join(OUTPUT_ROOT, 'ponytail', 'agents', 'openai.yaml');
  assert.equal(fs.readFileSync(configPath, 'utf8'), OPENAI_CONFIG);
  assert.match(OPENAI_CONFIG, /  allow_implicit_invocation: false\n/);
  assert.match(OPENAI_CONFIG, /  products:\n    - codex\n$/);

  for (const name of ONE_SHOT_NAMES) {
    const oneShotConfig = fs.readFileSync(
      path.join(OUTPUT_ROOT, name, 'agents', 'openai.yaml'),
      'utf8',
    );
    assert.equal(oneShotConfig, ONE_SHOT_OPENAI_CONFIG);
    assert.equal(oneShotConfig.includes('allow_implicit_invocation'), false);
  }
});

test('all portable skills are product-gated out of Codex', () => {
  for (const name of NAMES) {
    const config = fs.readFileSync(portableConfigPath(name), 'utf8');
    assert.equal(config, PORTABLE_OPENAI_CONFIG, `${name} is still discoverable from the portable root`);
    assert.match(config, /    - chatgpt\n    - atlas\n$/);
    assert.equal(config.includes('    - codex\n'), false);
  }
});

for (const name of ONE_SHOT_NAMES) {
  test(`${name}: committed Codex skill is the canonical source byte for byte`, () => {
    assert.deepEqual(
      fs.readFileSync(outPath(name)),
      fs.readFileSync(canonicalPath(name)),
      'stale — run: node scripts/build-codex-skills.js',
    );
  });
}
